import {
  _3dRotateIcon,
  AdminIcon,
  AdminBadgeIcon,
  AirdropIcon,
  AlignCenterIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AnalyticsIcon,
  AngleIcon,
  AnnouncementIcon,
  AppStoreIcon,
  AppStoreFillIcon,
  AppsIcon,
  ArchiveIcon,
  AttachmentIcon,
  AudioIcon,
  AudioFillIcon,
  AudioRectIcon,
  AudioRectFillIcon,
  BackIcon,
  BadgeIcon,
  BadgeAwardIcon,
  BadgeCheckIcon,
  BadgeCheckFillIcon,
  BadgeFillIcon,
  BagIcon,
  BagAddIcon,
  BagFillIcon,
  BagRemoveIcon,
  BankIcon,
  BatteryIcon,
  BatteryBoltIcon,
  BatteryBoltFillIcon,
  BatteryBoltHalfIcon,
  BatteryExclamationIcon,
  BatteryFillIcon,
  BatteryHalfIcon,
  BellIcon,
  BellFillIcon,
  BellOffIcon,
  BellOffFillIcon,
  BlueskyIcon,
  BlueskyFillIcon,
  BoltIcon,
  BoltCircleIcon,
  BoltDocsIcon,
  BoltStarsIcon,
  BoundingBoxIcon,
  BoundingBoxFillIcon,
  BriefcaseIcon,
  BrightnessKeyboardIcon,
  BrightnessKeyboardLowIcon,
  BrightnessLowIcon,
  BrightnessLowFillIcon,
  BroadcastIcon,
  BroadcastPinIcon,
  BugIcon,
  BugFillIcon,
  CalculatorIcon,
  CalculatorFillIcon,
  CameraIcon,
  CameraFillIcon,
  CapsuleIcon,
  CaptionsIcon,
  CaptionsFillIcon,
  CarIcon,
  CarFillIcon,
  CardIcon,
  CardAddIcon,
  CardListIcon,
  CardTextIcon,
  ChannelIcon,
  ChannelPrivateIcon,
  ChannelsIcon,
  CheckBoxIcon,
  CheckCircleIcon,
  CheckCircleFillIcon,
  CheckMarkIcon,
  CheckboxCheckedIcon,
  CheckmarkAllIcon,
  ClipboardIcon,
  ClipboardAddIcon,
  ClipboardAnalyticsIcon,
  ClipboardCancelIcon,
  ClipboardLikeIcon,
  ClipboardStarIcon,
  ClipboardTextIcon,
  ClockIcon,
  ClockFillIcon,
  CloudIcon,
  CloudDownloadIcon,
  CloudSunIcon,
  CloudSunFillIcon,
  CloudUploadIcon,
  CodeIcon,
  CommunityIcon,
  CompassIcon,
  CompassFillIcon,
  ComponentsIcon,
  ComponentsFillIcon,
  ContrastIcon,
  ControlsIcon,
  CopyIcon,
  CopyCheckIcon,
  CpuIcon,
  CreditCardIcon,
  CreditCardAddIcon,
  CreditCardBackIcon,
  CreditCardCheckIcon,
  CreditCardExclamationIcon,
  CreditCardForbiddenIcon,
  CreditCardLikeIcon,
  CreditCardStarIcon,
  CreditCardTransferInIcon,
  CreditCardTransferOutIcon,
  CrosshairsIcon,
  DashboardMeterIcon,
  DeleteIcon,
  Diagram2Icon,
  Diagram3Icon,
  DiceIcon,
  DiscordIcon,
  DiscordFillIcon,
  DiscordNudeIcon,
  DocsIcon,
  DocsFillIcon,
  DoorEnterIcon,
  DoorLeaveIcon,
  DownIcon,
  DownCaretIcon,
  DownFillIcon,
  EaselIcon,
  EaselAddIcon,
  EaselAddFillIcon,
  EaselAnalyticsIcon,
  EaselAnalyticsFillIcon,
  EaselFillIcon,
  EaselPlayIcon,
  EaselPlayFillIcon,
  EditIcon,
  EmailIcon,
  EmailBoltedIcon,
  EmailCheckIcon,
  EmailExclamationIcon,
  EmailFillIcon,
  EmailForbiddenIcon,
  EmailLikedIcon,
  EmailMoveIcon,
  EmailNewIcon,
  EmailStarredIcon,
  EmbedIcon,
  EmojiIcon,
  EnterIcon,
  EventAddIcon,
  EventAnalyticsIcon,
  EventCancelIcon,
  EventCheckIcon,
  EventCodeIcon,
  EventLikeIcon,
  EventMoveIcon,
  EventStarIcon,
  EverythingIcon,
  ExpandIcon,
  ExploreIcon,
  ExtendHorizontalIcon,
  ExtendVerticalIcon,
  ExternalIcon,
  ExternalFillIcon,
  FacebookIcon,
  FacebookFillIcon,
  FigmaIcon,
  FigmaFillIcon,
  FilterIcon,
  FilterFillIcon,
  FlagIcon,
  FlagFillIcon,
  FoodIcon,
  ForbiddenIcon,
  FormIcon,
  FormClearIcon,
  ForwardIcon,
  FreezeIcon,
  FriendIcon,
  FullscreenIcon,
  FullscreenExitIcon,
  GameControllerIcon,
  GameControllerWiredIcon,
  GirlIcon,
  GithubIcon,
  GithubFillIcon,
  GlassesIcon,
  GlassesFillIcon,
  GoogleIcon,
  GoogleFillIcon,
  GridIcon,
  GridColRowsIcon,
  GridColRowsFillIcon,
  GridColsIcon,
  GridColsFillIcon,
  GridFillIcon,
  GridRowColsIcon,
  GridRowColsFillIcon,
  GridRowsIcon,
  GridRowsFillIcon,
  GroupIcon,
  HddIcon,
  HddRackIcon,
  HddStackIcon,
  HeadphonesIcon,
  HeadphonesFillIcon,
  HelpIcon,
  HexagonIcon,
  HexagonFillIcon,
  HistoryIcon,
  HolderIcon,
  HomeIcon,
  HouseplantIcon,
  IdeaIcon,
  ImportantIcon,
  ImportantFillIcon,
  InfoIcon,
  InputDrawIcon,
  InputEditIcon,
  InserterIcon,
  InstagramIcon,
  InstagramFillIcon,
  LaptopIcon,
  LaptopFillIcon,
  LeaderIcon,
  LightbulbIcon,
  LightbulbFillIcon,
  LightbulbHighIcon,
  LightbulbHighFillIcon,
  LightbulbLowIcon,
  LightbulbLowFillIcon,
  LightbulbOffIcon,
  LightbulbOffFillIcon,
  LikeIcon,
  LikeFillIcon,
  LinkIcon,
  ListIcon,
  ListBulletedIcon,
  ListCheckedIcon,
  ListCheckedMixedIcon,
  ListMagicIcon,
  ListUncheckedIcon,
  MagnetIcon,
  MagnetFillIcon,
  MapAppIcon,
  MapPinIcon,
  MarkdownIcon,
  MastodonIcon,
  MastodonFillIcon,
  MediumIcon,
  MediumFillIcon,
  MegaphoneIcon,
  MegaphoneFillIcon,
  MehIcon,
  MemberAddIcon,
  MemberRemoveIcon,
  MentionIcon,
  MenuIcon,
  MessageIcon,
  MessageConversationIcon,
  MessageExclamationIcon,
  MessageExclamationFillIcon,
  MessageFillIcon,
  MessageNewIcon,
  MessageSimpleIcon,
  MessageSimpleFillIcon,
  MessageSimpleNewIcon,
  MessengerIcon,
  MessengerFillIcon,
  MicIcon,
  MicFillIcon,
  MicOffIcon,
  MicOffFillIcon,
  MicRetroIcon,
  MinusIcon,
  MinusFillIcon,
  MoonIcon,
  MoonCloudIcon,
  MoonCloudFillIcon,
  MoonFillIcon,
  MoonStarIcon,
  MoonStarFillIcon,
  MoreIcon,
  MoreFillIcon,
  MoreVerticalIcon,
  MoveIcon,
  MugIcon,
  MugFillIcon,
  MugHotIcon,
  MugHotFillIcon,
  MuteIcon,
  NotificationIcon,
  NotificationFillIcon,
  NotificationOffIcon,
  NotificationOffFillIcon,
  NutIcon,
  ObsNudeIcon,
  PackageIcon,
  PackageSeamIcon,
  PartyIcon,
  PauseCircleIcon,
  PauseCircleFillIcon,
  PaymentIcon,
  PaymentDocsIcon,
  PaymentTransferIcon,
  PaypalIcon,
  PaypalFillIcon,
  People2Icon,
  People3Icon,
  People3CenterIcon,
  PersonIcon,
  PersonBadgeIcon,
  PersonBadgeFillIcon,
  PersonCardIcon,
  PhoneIcon,
  PhoneBoltIcon,
  PhoneFillIcon,
  PhoneVibrateIcon,
  PhotoIcon,
  PhotoFillIcon,
  PhotosIcon,
  PhotosFillIcon,
  PieChartIcon,
  PieChartFillIcon,
  PinIcon,
  PinFillIcon,
  PlayCircleIcon,
  PlayCircleFillIcon,
  PlusIcon,
  PlusFillIcon,
  PlusSlashMinusIcon,
  PositionBottomIcon,
  PositionBottomLeftIcon,
  PositionBottomRightIcon,
  PositionCenterIcon,
  PositionLeftIcon,
  PositionRightIcon,
  PositionTopIcon,
  PositionTopLeftIcon,
  PositionTopRightIcon,
  PostIcon,
  PostCancelIcon,
  PostFillIcon,
  PrintIcon,
  PrivacyIcon,
  PrivateIcon,
  PrivateOutlineIcon,
  PrivateUnlockedIcon,
  ProfileIcon,
  ProfileAddIcon,
  ProfileCheckIcon,
  ProfileExclamationIcon,
  ProfileFillIcon,
  ProfileForbiddenIcon,
  ProfileLikeIcon,
  ProfileStarIcon,
  QrCodeIcon,
  QuoteIcon,
  RainbowIcon,
  RelaxedIcon,
  RepIcon,
  ReplyIcon,
  ResourcesIcon,
  RightCaretIcon,
  RouteIcon,
  RssIcon,
  RssFillIcon,
  SadIcon,
  SamIcon,
  SearchIcon,
  SearchFillIcon,
  SearchMagicIcon,
  SearchMagicFillIcon,
  SendIcon,
  SendFillIcon,
  SettingsIcon,
  ShareIcon,
  ShirtIcon,
  ShirtFillIcon,
  SlackIcon,
  SlackFillIcon,
  SolarIcon,
  SortAscIcon,
  SortDescIcon,
  SortHorizontalIcon,
  SortVerticalIcon,
  StarIcon,
  StarFillIcon,
  StarHalfIcon,
  StickerIcon,
  StopwatchIcon,
  StopwatchFillIcon,
  SunIcon,
  SunFillIcon,
  SunglassesIcon,
  SunriseIcon,
  SunriseFillIcon,
  SupportIcon,
  SupportFillIcon,
  SwitchOffIcon,
  SwitchOnIcon,
  SwitchesIcon,
  SwitchesFillIcon,
  SwitchesMixedIcon,
  TabletIcon,
  TabletDrawIcon,
  TabletFillIcon,
  TentIcon,
  TentStarsIcon,
  TerminalIcon,
  TerminalAddIcon,
  TerminalAddFillIcon,
  TerminalCancelIcon,
  TerminalCancelFillIcon,
  TerminalCheckIcon,
  TerminalCheckFillIcon,
  TerminalExclamationIcon,
  TerminalExclamationFillIcon,
  TerminalFillIcon,
  TerminalForbiddenIcon,
  TerminalForbiddenFillIcon,
  TerminalLikeIcon,
  TerminalLikeFillIcon,
  TerminalPromptIcon,
  TerminalStarIcon,
  TerminalStarFillIcon,
  ThermometerIcon,
  ThermometerFillIcon,
  ThermometerHalfIcon,
  ThermometerLowIcon,
  ThreadIcon,
  ThreadsIcon,
  ThreadsFillIcon,
  ThumbsDownIcon,
  ThumbsDownFillIcon,
  ThumbsUpIcon,
  ThumbsUpFillIcon,
  TiktokIcon,
  TiktokFillIcon,
  TimerIcon,
  TransactionsIcon,
  TransferHorizontalIcon,
  TransferVerticalIcon,
  TransfersHorizontalIcon,
  TransfersVerticalIcon,
  TransitIcon,
  TransitRailsIcon,
  TransitWheelsIcon,
  TrophyIcon,
  TrophyFillIcon,
  TvIcon,
  TvCastIcon,
  TvCastFillIcon,
  TvFillIcon,
  TwitchIcon,
  TwitchFillIcon,
  TwitchNudeIcon,
  TwitterIcon,
  TwitterFillIcon,
  TwitterxIcon,
  TwitterxFillIcon,
  TypographyIcon,
  UpIcon,
  UpCaretIcon,
  UpFillIcon,
  ViewIcon,
  ViewBackIcon,
  ViewCloseIcon,
  ViewCloseSmallIcon,
  ViewFillIcon,
  ViewForwardIcon,
  ViewHideIcon,
  ViewReloadIcon,
  VrIcon,
  VrFillIcon,
  WandIcon,
  WandStarsIcon,
  WaveformIcon,
  WebIcon,
  WelcomeIcon,
  WifiIcon,
  WindIcon,
  WineGlassIcon,
  WineGlassFillIcon,
  YoutubeIcon,
  YoutubeFillIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from 'lolicon'

export const Icons = [
  { name: '_3dRotate', icon: _3dRotateIcon },
  { name: 'Admin', icon: AdminIcon },
  { name: 'AdminBadge', icon: AdminBadgeIcon },
  { name: 'Airdrop', icon: AirdropIcon },
  { name: 'AlignCenter', icon: AlignCenterIcon },
  { name: 'AlignLeft', icon: AlignLeftIcon },
  { name: 'AlignRight', icon: AlignRightIcon },
  { name: 'Analytics', icon: AnalyticsIcon },
  { name: 'Angle', icon: AngleIcon },
  { name: 'Announcement', icon: AnnouncementIcon },
  { name: 'AppStore', icon: AppStoreIcon },
  { name: 'AppStoreFill', icon: AppStoreFillIcon },
  { name: 'Apps', icon: AppsIcon },
  { name: 'Archive', icon: ArchiveIcon },
  { name: 'Attachment', icon: AttachmentIcon },
  { name: 'Audio', icon: AudioIcon },
  { name: 'AudioFill', icon: AudioFillIcon },
  { name: 'AudioRect', icon: AudioRectIcon },
  { name: 'AudioRectFill', icon: AudioRectFillIcon },
  { name: 'Back', icon: BackIcon },
  { name: 'Badge', icon: BadgeIcon },
  { name: 'BadgeAward', icon: BadgeAwardIcon },
  { name: 'BadgeCheck', icon: BadgeCheckIcon },
  { name: 'BadgeCheckFill', icon: BadgeCheckFillIcon },
  { name: 'BadgeFill', icon: BadgeFillIcon },
  { name: 'Bag', icon: BagIcon },
  { name: 'BagAdd', icon: BagAddIcon },
  { name: 'BagFill', icon: BagFillIcon },
  { name: 'BagRemove', icon: BagRemoveIcon },
  { name: 'Bank', icon: BankIcon },
  { name: 'Battery', icon: BatteryIcon },
  { name: 'BatteryBolt', icon: BatteryBoltIcon },
  { name: 'BatteryBoltFill', icon: BatteryBoltFillIcon },
  { name: 'BatteryBoltHalf', icon: BatteryBoltHalfIcon },
  { name: 'BatteryExclamation', icon: BatteryExclamationIcon },
  { name: 'BatteryFill', icon: BatteryFillIcon },
  { name: 'BatteryHalf', icon: BatteryHalfIcon },
  { name: 'Bell', icon: BellIcon },
  { name: 'BellFill', icon: BellFillIcon },
  { name: 'BellOff', icon: BellOffIcon },
  { name: 'BellOffFill', icon: BellOffFillIcon },
  { name: 'Bluesky', icon: BlueskyIcon },
  { name: 'BlueskyFill', icon: BlueskyFillIcon },
  { name: 'Bolt', icon: BoltIcon },
  { name: 'BoltCircle', icon: BoltCircleIcon },
  { name: 'BoltDocs', icon: BoltDocsIcon },
  { name: 'BoltStars', icon: BoltStarsIcon },
  { name: 'BoundingBox', icon: BoundingBoxIcon },
  { name: 'BoundingBoxFill', icon: BoundingBoxFillIcon },
  { name: 'Briefcase', icon: BriefcaseIcon },
  { name: 'BrightnessKeyboard', icon: BrightnessKeyboardIcon },
  { name: 'BrightnessKeyboardLow', icon: BrightnessKeyboardLowIcon },
  { name: 'BrightnessLow', icon: BrightnessLowIcon },
  { name: 'BrightnessLowFill', icon: BrightnessLowFillIcon },
  { name: 'Broadcast', icon: BroadcastIcon },
  { name: 'BroadcastPin', icon: BroadcastPinIcon },
  { name: 'Bug', icon: BugIcon },
  { name: 'BugFill', icon: BugFillIcon },
  { name: 'Calculator', icon: CalculatorIcon },
  { name: 'CalculatorFill', icon: CalculatorFillIcon },
  { name: 'Camera', icon: CameraIcon },
  { name: 'CameraFill', icon: CameraFillIcon },
  { name: 'Capsule', icon: CapsuleIcon },
  { name: 'Captions', icon: CaptionsIcon },
  { name: 'CaptionsFill', icon: CaptionsFillIcon },
  { name: 'Car', icon: CarIcon },
  { name: 'CarFill', icon: CarFillIcon },
  { name: 'Card', icon: CardIcon },
  { name: 'CardAdd', icon: CardAddIcon },
  { name: 'CardList', icon: CardListIcon },
  { name: 'CardText', icon: CardTextIcon },
  { name: 'Channel', icon: ChannelIcon },
  { name: 'ChannelPrivate', icon: ChannelPrivateIcon },
  { name: 'Channels', icon: ChannelsIcon },
  { name: 'CheckBox', icon: CheckBoxIcon },
  { name: 'CheckCircle', icon: CheckCircleIcon },
  { name: 'CheckCircleFill', icon: CheckCircleFillIcon },
  { name: 'CheckMark', icon: CheckMarkIcon },
  { name: 'CheckboxChecked', icon: CheckboxCheckedIcon },
  { name: 'CheckmarkAll', icon: CheckmarkAllIcon },
  { name: 'Clipboard', icon: ClipboardIcon },
  { name: 'ClipboardAdd', icon: ClipboardAddIcon },
  { name: 'ClipboardAnalytics', icon: ClipboardAnalyticsIcon },
  { name: 'ClipboardCancel', icon: ClipboardCancelIcon },
  { name: 'ClipboardLike', icon: ClipboardLikeIcon },
  { name: 'ClipboardStar', icon: ClipboardStarIcon },
  { name: 'ClipboardText', icon: ClipboardTextIcon },
  { name: 'Clock', icon: ClockIcon },
  { name: 'ClockFill', icon: ClockFillIcon },
  { name: 'Cloud', icon: CloudIcon },
  { name: 'CloudDownload', icon: CloudDownloadIcon },
  { name: 'CloudSun', icon: CloudSunIcon },
  { name: 'CloudSunFill', icon: CloudSunFillIcon },
  { name: 'CloudUpload', icon: CloudUploadIcon },
  { name: 'Code', icon: CodeIcon },
  { name: 'Community', icon: CommunityIcon },
  { name: 'Compass', icon: CompassIcon },
  { name: 'CompassFill', icon: CompassFillIcon },
  { name: 'Components', icon: ComponentsIcon },
  { name: 'ComponentsFill', icon: ComponentsFillIcon },
  { name: 'Contrast', icon: ContrastIcon },
  { name: 'Controls', icon: ControlsIcon },
  { name: 'Copy', icon: CopyIcon },
  { name: 'CopyCheck', icon: CopyCheckIcon },
  { name: 'Cpu', icon: CpuIcon },
  { name: 'CreditCard', icon: CreditCardIcon },
  { name: 'CreditCardAdd', icon: CreditCardAddIcon },
  { name: 'CreditCardBack', icon: CreditCardBackIcon },
  { name: 'CreditCardCheck', icon: CreditCardCheckIcon },
  { name: 'CreditCardExclamation', icon: CreditCardExclamationIcon },
  { name: 'CreditCardForbidden', icon: CreditCardForbiddenIcon },
  { name: 'CreditCardLike', icon: CreditCardLikeIcon },
  { name: 'CreditCardStar', icon: CreditCardStarIcon },
  { name: 'CreditCardTransferIn', icon: CreditCardTransferInIcon },
  { name: 'CreditCardTransferOut', icon: CreditCardTransferOutIcon },
  { name: 'Crosshairs', icon: CrosshairsIcon },
  { name: 'DashboardMeter', icon: DashboardMeterIcon },
  { name: 'Delete', icon: DeleteIcon },
  { name: 'Diagram2', icon: Diagram2Icon },
  { name: 'Diagram3', icon: Diagram3Icon },
  { name: 'Dice', icon: DiceIcon },
  { name: 'Discord', icon: DiscordIcon },
  { name: 'DiscordFill', icon: DiscordFillIcon },
  { name: 'DiscordNude', icon: DiscordNudeIcon },
  { name: 'Docs', icon: DocsIcon },
  { name: 'DocsFill', icon: DocsFillIcon },
  { name: 'DoorEnter', icon: DoorEnterIcon },
  { name: 'DoorLeave', icon: DoorLeaveIcon },
  { name: 'Down', icon: DownIcon },
  { name: 'DownCaret', icon: DownCaretIcon },
  { name: 'DownFill', icon: DownFillIcon },
  { name: 'Easel', icon: EaselIcon },
  { name: 'EaselAdd', icon: EaselAddIcon },
  { name: 'EaselAddFill', icon: EaselAddFillIcon },
  { name: 'EaselAnalytics', icon: EaselAnalyticsIcon },
  { name: 'EaselAnalyticsFill', icon: EaselAnalyticsFillIcon },
  { name: 'EaselFill', icon: EaselFillIcon },
  { name: 'EaselPlay', icon: EaselPlayIcon },
  { name: 'EaselPlayFill', icon: EaselPlayFillIcon },
  { name: 'Edit', icon: EditIcon },
  { name: 'Email', icon: EmailIcon },
  { name: 'EmailBolted', icon: EmailBoltedIcon },
  { name: 'EmailCheck', icon: EmailCheckIcon },
  { name: 'EmailExclamation', icon: EmailExclamationIcon },
  { name: 'EmailFill', icon: EmailFillIcon },
  { name: 'EmailForbidden', icon: EmailForbiddenIcon },
  { name: 'EmailLiked', icon: EmailLikedIcon },
  { name: 'EmailMove', icon: EmailMoveIcon },
  { name: 'EmailNew', icon: EmailNewIcon },
  { name: 'EmailStarred', icon: EmailStarredIcon },
  { name: 'Embed', icon: EmbedIcon },
  { name: 'Emoji', icon: EmojiIcon },
  { name: 'Enter', icon: EnterIcon },
  { name: 'EventAdd', icon: EventAddIcon },
  { name: 'EventAnalytics', icon: EventAnalyticsIcon },
  { name: 'EventCancel', icon: EventCancelIcon },
  { name: 'EventCheck', icon: EventCheckIcon },
  { name: 'EventCode', icon: EventCodeIcon },
  { name: 'EventLike', icon: EventLikeIcon },
  { name: 'EventMove', icon: EventMoveIcon },
  { name: 'EventStar', icon: EventStarIcon },
  { name: 'Everything', icon: EverythingIcon },
  { name: 'Expand', icon: ExpandIcon },
  { name: 'Explore', icon: ExploreIcon },
  { name: 'ExtendHorizontal', icon: ExtendHorizontalIcon },
  { name: 'ExtendVertical', icon: ExtendVerticalIcon },
  { name: 'External', icon: ExternalIcon },
  { name: 'ExternalFill', icon: ExternalFillIcon },
  { name: 'Facebook', icon: FacebookIcon },
  { name: 'FacebookFill', icon: FacebookFillIcon },
  { name: 'Figma', icon: FigmaIcon },
  { name: 'FigmaFill', icon: FigmaFillIcon },
  { name: 'Filter', icon: FilterIcon },
  { name: 'FilterFill', icon: FilterFillIcon },
  { name: 'Flag', icon: FlagIcon },
  { name: 'FlagFill', icon: FlagFillIcon },
  { name: 'Food', icon: FoodIcon },
  { name: 'Forbidden', icon: ForbiddenIcon },
  { name: 'Form', icon: FormIcon },
  { name: 'FormClear', icon: FormClearIcon },
  { name: 'Forward', icon: ForwardIcon },
  { name: 'Freeze', icon: FreezeIcon },
  { name: 'Friend', icon: FriendIcon },
  { name: 'Fullscreen', icon: FullscreenIcon },
  { name: 'FullscreenExit', icon: FullscreenExitIcon },
  { name: 'GameController', icon: GameControllerIcon },
  { name: 'GameControllerWired', icon: GameControllerWiredIcon },
  { name: 'Girl', icon: GirlIcon },
  { name: 'Github', icon: GithubIcon },
  { name: 'GithubFill', icon: GithubFillIcon },
  { name: 'Glasses', icon: GlassesIcon },
  { name: 'GlassesFill', icon: GlassesFillIcon },
  { name: 'Google', icon: GoogleIcon },
  { name: 'GoogleFill', icon: GoogleFillIcon },
  { name: 'Grid', icon: GridIcon },
  { name: 'GridColRows', icon: GridColRowsIcon },
  { name: 'GridColRowsFill', icon: GridColRowsFillIcon },
  { name: 'GridCols', icon: GridColsIcon },
  { name: 'GridColsFill', icon: GridColsFillIcon },
  { name: 'GridFill', icon: GridFillIcon },
  { name: 'GridRowCols', icon: GridRowColsIcon },
  { name: 'GridRowColsFill', icon: GridRowColsFillIcon },
  { name: 'GridRows', icon: GridRowsIcon },
  { name: 'GridRowsFill', icon: GridRowsFillIcon },
  { name: 'Group', icon: GroupIcon },
  { name: 'Hdd', icon: HddIcon },
  { name: 'HddRack', icon: HddRackIcon },
  { name: 'HddStack', icon: HddStackIcon },
  { name: 'Headphones', icon: HeadphonesIcon },
  { name: 'HeadphonesFill', icon: HeadphonesFillIcon },
  { name: 'Help', icon: HelpIcon },
  { name: 'Hexagon', icon: HexagonIcon },
  { name: 'HexagonFill', icon: HexagonFillIcon },
  { name: 'History', icon: HistoryIcon },
  { name: 'Holder', icon: HolderIcon },
  { name: 'Home', icon: HomeIcon },
  { name: 'Houseplant', icon: HouseplantIcon },
  { name: 'Idea', icon: IdeaIcon },
  { name: 'Important', icon: ImportantIcon },
  { name: 'ImportantFill', icon: ImportantFillIcon },
  { name: 'Info', icon: InfoIcon },
  { name: 'InputDraw', icon: InputDrawIcon },
  { name: 'InputEdit', icon: InputEditIcon },
  { name: 'Inserter', icon: InserterIcon },
  { name: 'Instagram', icon: InstagramIcon },
  { name: 'InstagramFill', icon: InstagramFillIcon },
  { name: 'Laptop', icon: LaptopIcon },
  { name: 'LaptopFill', icon: LaptopFillIcon },
  { name: 'Leader', icon: LeaderIcon },
  { name: 'Lightbulb', icon: LightbulbIcon },
  { name: 'LightbulbFill', icon: LightbulbFillIcon },
  { name: 'LightbulbHigh', icon: LightbulbHighIcon },
  { name: 'LightbulbHighFill', icon: LightbulbHighFillIcon },
  { name: 'LightbulbLow', icon: LightbulbLowIcon },
  { name: 'LightbulbLowFill', icon: LightbulbLowFillIcon },
  { name: 'LightbulbOff', icon: LightbulbOffIcon },
  { name: 'LightbulbOffFill', icon: LightbulbOffFillIcon },
  { name: 'Like', icon: LikeIcon },
  { name: 'LikeFill', icon: LikeFillIcon },
  { name: 'Link', icon: LinkIcon },
  { name: 'List', icon: ListIcon },
  { name: 'ListBulleted', icon: ListBulletedIcon },
  { name: 'ListChecked', icon: ListCheckedIcon },
  { name: 'ListCheckedMixed', icon: ListCheckedMixedIcon },
  { name: 'ListMagic', icon: ListMagicIcon },
  { name: 'ListUnchecked', icon: ListUncheckedIcon },
  { name: 'Magnet', icon: MagnetIcon },
  { name: 'MagnetFill', icon: MagnetFillIcon },
  { name: 'MapApp', icon: MapAppIcon },
  { name: 'MapPin', icon: MapPinIcon },
  { name: 'Markdown', icon: MarkdownIcon },
  { name: 'Mastodon', icon: MastodonIcon },
  { name: 'MastodonFill', icon: MastodonFillIcon },
  { name: 'Medium', icon: MediumIcon },
  { name: 'MediumFill', icon: MediumFillIcon },
  { name: 'Megaphone', icon: MegaphoneIcon },
  { name: 'MegaphoneFill', icon: MegaphoneFillIcon },
  { name: 'Meh', icon: MehIcon },
  { name: 'MemberAdd', icon: MemberAddIcon },
  { name: 'MemberRemove', icon: MemberRemoveIcon },
  { name: 'Mention', icon: MentionIcon },
  { name: 'Menu', icon: MenuIcon },
  { name: 'Message', icon: MessageIcon },
  { name: 'MessageConversation', icon: MessageConversationIcon },
  { name: 'MessageExclamation', icon: MessageExclamationIcon },
  { name: 'MessageExclamationFill', icon: MessageExclamationFillIcon },
  { name: 'MessageFill', icon: MessageFillIcon },
  { name: 'MessageNew', icon: MessageNewIcon },
  { name: 'MessageSimple', icon: MessageSimpleIcon },
  { name: 'MessageSimpleFill', icon: MessageSimpleFillIcon },
  { name: 'MessageSimpleNew', icon: MessageSimpleNewIcon },
  { name: 'Messenger', icon: MessengerIcon },
  { name: 'MessengerFill', icon: MessengerFillIcon },
  { name: 'Mic', icon: MicIcon },
  { name: 'MicFill', icon: MicFillIcon },
  { name: 'MicOff', icon: MicOffIcon },
  { name: 'MicOffFill', icon: MicOffFillIcon },
  { name: 'MicRetro', icon: MicRetroIcon },
  { name: 'Minus', icon: MinusIcon },
  { name: 'MinusFill', icon: MinusFillIcon },
  { name: 'Moon', icon: MoonIcon },
  { name: 'MoonCloud', icon: MoonCloudIcon },
  { name: 'MoonCloudFill', icon: MoonCloudFillIcon },
  { name: 'MoonFill', icon: MoonFillIcon },
  { name: 'MoonStar', icon: MoonStarIcon },
  { name: 'MoonStarFill', icon: MoonStarFillIcon },
  { name: 'More', icon: MoreIcon },
  { name: 'MoreFill', icon: MoreFillIcon },
  { name: 'MoreVertical', icon: MoreVerticalIcon },
  { name: 'Move', icon: MoveIcon },
  { name: 'Mug', icon: MugIcon },
  { name: 'MugFill', icon: MugFillIcon },
  { name: 'MugHot', icon: MugHotIcon },
  { name: 'MugHotFill', icon: MugHotFillIcon },
  { name: 'Mute', icon: MuteIcon },
  { name: 'Notification', icon: NotificationIcon },
  { name: 'NotificationFill', icon: NotificationFillIcon },
  { name: 'NotificationOff', icon: NotificationOffIcon },
  { name: 'NotificationOffFill', icon: NotificationOffFillIcon },
  { name: 'Nut', icon: NutIcon },
  { name: 'ObsNude', icon: ObsNudeIcon },
  { name: 'Package', icon: PackageIcon },
  { name: 'PackageSeam', icon: PackageSeamIcon },
  { name: 'Party', icon: PartyIcon },
  { name: 'PauseCircle', icon: PauseCircleIcon },
  { name: 'PauseCircleFill', icon: PauseCircleFillIcon },
  { name: 'Payment', icon: PaymentIcon },
  { name: 'PaymentDocs', icon: PaymentDocsIcon },
  { name: 'PaymentTransfer', icon: PaymentTransferIcon },
  { name: 'Paypal', icon: PaypalIcon },
  { name: 'PaypalFill', icon: PaypalFillIcon },
  { name: 'People2', icon: People2Icon },
  { name: 'People3', icon: People3Icon },
  { name: 'People3Center', icon: People3CenterIcon },
  { name: 'Person', icon: PersonIcon },
  { name: 'PersonBadge', icon: PersonBadgeIcon },
  { name: 'PersonBadgeFill', icon: PersonBadgeFillIcon },
  { name: 'PersonCard', icon: PersonCardIcon },
  { name: 'Phone', icon: PhoneIcon },
  { name: 'PhoneBolt', icon: PhoneBoltIcon },
  { name: 'PhoneFill', icon: PhoneFillIcon },
  { name: 'PhoneVibrate', icon: PhoneVibrateIcon },
  { name: 'Photo', icon: PhotoIcon },
  { name: 'PhotoFill', icon: PhotoFillIcon },
  { name: 'Photos', icon: PhotosIcon },
  { name: 'PhotosFill', icon: PhotosFillIcon },
  { name: 'PieChart', icon: PieChartIcon },
  { name: 'PieChartFill', icon: PieChartFillIcon },
  { name: 'Pin', icon: PinIcon },
  { name: 'PinFill', icon: PinFillIcon },
  { name: 'PlayCircle', icon: PlayCircleIcon },
  { name: 'PlayCircleFill', icon: PlayCircleFillIcon },
  { name: 'Plus', icon: PlusIcon },
  { name: 'PlusFill', icon: PlusFillIcon },
  { name: 'PlusSlashMinus', icon: PlusSlashMinusIcon },
  { name: 'PositionBottom', icon: PositionBottomIcon },
  { name: 'PositionBottomLeft', icon: PositionBottomLeftIcon },
  { name: 'PositionBottomRight', icon: PositionBottomRightIcon },
  { name: 'PositionCenter', icon: PositionCenterIcon },
  { name: 'PositionLeft', icon: PositionLeftIcon },
  { name: 'PositionRight', icon: PositionRightIcon },
  { name: 'PositionTop', icon: PositionTopIcon },
  { name: 'PositionTopLeft', icon: PositionTopLeftIcon },
  { name: 'PositionTopRight', icon: PositionTopRightIcon },
  { name: 'Post', icon: PostIcon },
  { name: 'PostCancel', icon: PostCancelIcon },
  { name: 'PostFill', icon: PostFillIcon },
  { name: 'Print', icon: PrintIcon },
  { name: 'Privacy', icon: PrivacyIcon },
  { name: 'Private', icon: PrivateIcon },
  { name: 'PrivateOutline', icon: PrivateOutlineIcon },
  { name: 'PrivateUnlocked', icon: PrivateUnlockedIcon },
  { name: 'Profile', icon: ProfileIcon },
  { name: 'ProfileAdd', icon: ProfileAddIcon },
  { name: 'ProfileCheck', icon: ProfileCheckIcon },
  { name: 'ProfileExclamation', icon: ProfileExclamationIcon },
  { name: 'ProfileFill', icon: ProfileFillIcon },
  { name: 'ProfileForbidden', icon: ProfileForbiddenIcon },
  { name: 'ProfileLike', icon: ProfileLikeIcon },
  { name: 'ProfileStar', icon: ProfileStarIcon },
  { name: 'QrCode', icon: QrCodeIcon },
  { name: 'Quote', icon: QuoteIcon },
  { name: 'Rainbow', icon: RainbowIcon },
  { name: 'Relaxed', icon: RelaxedIcon },
  { name: 'Rep', icon: RepIcon },
  { name: 'Reply', icon: ReplyIcon },
  { name: 'Resources', icon: ResourcesIcon },
  { name: 'RightCaret', icon: RightCaretIcon },
  { name: 'Route', icon: RouteIcon },
  { name: 'Rss', icon: RssIcon },
  { name: 'RssFill', icon: RssFillIcon },
  { name: 'Sad', icon: SadIcon },
  { name: 'Sam', icon: SamIcon },
  { name: 'Search', icon: SearchIcon },
  { name: 'SearchFill', icon: SearchFillIcon },
  { name: 'SearchMagic', icon: SearchMagicIcon },
  { name: 'SearchMagicFill', icon: SearchMagicFillIcon },
  { name: 'Send', icon: SendIcon },
  { name: 'SendFill', icon: SendFillIcon },
  { name: 'Settings', icon: SettingsIcon },
  { name: 'Share', icon: ShareIcon },
  { name: 'Shirt', icon: ShirtIcon },
  { name: 'ShirtFill', icon: ShirtFillIcon },
  { name: 'Slack', icon: SlackIcon },
  { name: 'SlackFill', icon: SlackFillIcon },
  { name: 'Solar', icon: SolarIcon },
  { name: 'SortAsc', icon: SortAscIcon },
  { name: 'SortDesc', icon: SortDescIcon },
  { name: 'SortHorizontal', icon: SortHorizontalIcon },
  { name: 'SortVertical', icon: SortVerticalIcon },
  { name: 'Star', icon: StarIcon },
  { name: 'StarFill', icon: StarFillIcon },
  { name: 'StarHalf', icon: StarHalfIcon },
  { name: 'Sticker', icon: StickerIcon },
  { name: 'Stopwatch', icon: StopwatchIcon },
  { name: 'StopwatchFill', icon: StopwatchFillIcon },
  { name: 'Sun', icon: SunIcon },
  { name: 'SunFill', icon: SunFillIcon },
  { name: 'Sunglasses', icon: SunglassesIcon },
  { name: 'Sunrise', icon: SunriseIcon },
  { name: 'SunriseFill', icon: SunriseFillIcon },
  { name: 'Support', icon: SupportIcon },
  { name: 'SupportFill', icon: SupportFillIcon },
  { name: 'SwitchOff', icon: SwitchOffIcon },
  { name: 'SwitchOn', icon: SwitchOnIcon },
  { name: 'Switches', icon: SwitchesIcon },
  { name: 'SwitchesFill', icon: SwitchesFillIcon },
  { name: 'SwitchesMixed', icon: SwitchesMixedIcon },
  { name: 'Tablet', icon: TabletIcon },
  { name: 'TabletDraw', icon: TabletDrawIcon },
  { name: 'TabletFill', icon: TabletFillIcon },
  { name: 'Tent', icon: TentIcon },
  { name: 'TentStars', icon: TentStarsIcon },
  { name: 'Terminal', icon: TerminalIcon },
  { name: 'TerminalAdd', icon: TerminalAddIcon },
  { name: 'TerminalAddFill', icon: TerminalAddFillIcon },
  { name: 'TerminalCancel', icon: TerminalCancelIcon },
  { name: 'TerminalCancelFill', icon: TerminalCancelFillIcon },
  { name: 'TerminalCheck', icon: TerminalCheckIcon },
  { name: 'TerminalCheckFill', icon: TerminalCheckFillIcon },
  { name: 'TerminalExclamation', icon: TerminalExclamationIcon },
  { name: 'TerminalExclamationFill', icon: TerminalExclamationFillIcon },
  { name: 'TerminalFill', icon: TerminalFillIcon },
  { name: 'TerminalForbidden', icon: TerminalForbiddenIcon },
  { name: 'TerminalForbiddenFill', icon: TerminalForbiddenFillIcon },
  { name: 'TerminalLike', icon: TerminalLikeIcon },
  { name: 'TerminalLikeFill', icon: TerminalLikeFillIcon },
  { name: 'TerminalPrompt', icon: TerminalPromptIcon },
  { name: 'TerminalStar', icon: TerminalStarIcon },
  { name: 'TerminalStarFill', icon: TerminalStarFillIcon },
  { name: 'Thermometer', icon: ThermometerIcon },
  { name: 'ThermometerFill', icon: ThermometerFillIcon },
  { name: 'ThermometerHalf', icon: ThermometerHalfIcon },
  { name: 'ThermometerLow', icon: ThermometerLowIcon },
  { name: 'Thread', icon: ThreadIcon },
  { name: 'Threads', icon: ThreadsIcon },
  { name: 'ThreadsFill', icon: ThreadsFillIcon },
  { name: 'ThumbsDown', icon: ThumbsDownIcon },
  { name: 'ThumbsDownFill', icon: ThumbsDownFillIcon },
  { name: 'ThumbsUp', icon: ThumbsUpIcon },
  { name: 'ThumbsUpFill', icon: ThumbsUpFillIcon },
  { name: 'Tiktok', icon: TiktokIcon },
  { name: 'TiktokFill', icon: TiktokFillIcon },
  { name: 'Timer', icon: TimerIcon },
  { name: 'Transactions', icon: TransactionsIcon },
  { name: 'TransferHorizontal', icon: TransferHorizontalIcon },
  { name: 'TransferVertical', icon: TransferVerticalIcon },
  { name: 'TransfersHorizontal', icon: TransfersHorizontalIcon },
  { name: 'TransfersVertical', icon: TransfersVerticalIcon },
  { name: 'Transit', icon: TransitIcon },
  { name: 'TransitRails', icon: TransitRailsIcon },
  { name: 'TransitWheels', icon: TransitWheelsIcon },
  { name: 'Trophy', icon: TrophyIcon },
  { name: 'TrophyFill', icon: TrophyFillIcon },
  { name: 'Tv', icon: TvIcon },
  { name: 'TvCast', icon: TvCastIcon },
  { name: 'TvCastFill', icon: TvCastFillIcon },
  { name: 'TvFill', icon: TvFillIcon },
  { name: 'Twitch', icon: TwitchIcon },
  { name: 'TwitchFill', icon: TwitchFillIcon },
  { name: 'TwitchNude', icon: TwitchNudeIcon },
  { name: 'Twitter', icon: TwitterIcon },
  { name: 'TwitterFill', icon: TwitterFillIcon },
  { name: 'Twitterx', icon: TwitterxIcon },
  { name: 'TwitterxFill', icon: TwitterxFillIcon },
  { name: 'Typography', icon: TypographyIcon },
  { name: 'Up', icon: UpIcon },
  { name: 'UpCaret', icon: UpCaretIcon },
  { name: 'UpFill', icon: UpFillIcon },
  { name: 'View', icon: ViewIcon },
  { name: 'ViewBack', icon: ViewBackIcon },
  { name: 'ViewClose', icon: ViewCloseIcon },
  { name: 'ViewCloseSmall', icon: ViewCloseSmallIcon },
  { name: 'ViewFill', icon: ViewFillIcon },
  { name: 'ViewForward', icon: ViewForwardIcon },
  { name: 'ViewHide', icon: ViewHideIcon },
  { name: 'ViewReload', icon: ViewReloadIcon },
  { name: 'Vr', icon: VrIcon },
  { name: 'VrFill', icon: VrFillIcon },
  { name: 'Wand', icon: WandIcon },
  { name: 'WandStars', icon: WandStarsIcon },
  { name: 'Waveform', icon: WaveformIcon },
  { name: 'Web', icon: WebIcon },
  { name: 'Welcome', icon: WelcomeIcon },
  { name: 'Wifi', icon: WifiIcon },
  { name: 'Wind', icon: WindIcon },
  { name: 'WineGlass', icon: WineGlassIcon },
  { name: 'WineGlassFill', icon: WineGlassFillIcon },
  { name: 'Youtube', icon: YoutubeIcon },
  { name: 'YoutubeFill', icon: YoutubeFillIcon },
  { name: 'ZoomIn', icon: ZoomInIcon },
  { name: 'ZoomOut', icon: ZoomOutIcon },
]
